### ISSUE TITLE
jquery version conflicts

### ISSUE THREAD

**Issue by Gavarni** [sathomas/acc-wizard#28]
Hi,

I just tried to test your accordian wozard with my project. I am using jquery 3.1 however im not sure which version is ok with your accordian. jQuery 1.11 works but i need 3.1 is there going to be an upgraded version of accordian wizard?

Thanks in advance

Gavarni

**Comment by sathomas** [comment]
Hi Gavarni,

Thanks for the question. Unfortunately, I find that I don't really have time to spend on this code right now. You're welcome to submit a pull request with any fixes, but I won't be able to do any work myself.

(I'm going to close this issue with this answer, but that doesn't mean it isn't valid.)
